### ISSUE TITLE
Explanation of commnad line options

### ISSUE THREAD

**Issue by laytonjbgmail** [hariharan-devarajan/dlio_benchmark#4]
I just started looking at DLIO and I was wondering if there is a document that explains the options used with the mpirun command?

Thanks!

**Comment by hariharan-devarajan** [comment]
My apologies for not having good documentation for this.

Take a look at https://github.com/hariharan-devarajan/dlio_benchmark/blob/master/scripts/cosmic.sh script.

This has  been tested on Theta machine in ALCF. 

If you have issues running please let me know.

**Comment by hariharan-devarajan** [comment]
for commond line options in DLIO you can do a -h on the ${DLIO_ROOT}/src/dlio_benchmark.py

**Comment by laytonjbgmail** [comment]
Thanks for your quick reply. 

Two things - First, I can't get DLIO installed and running (that's a different ticket) so I can't use "-h".

Second - the script you pointed me to does not explain what the options mean. I'm looking for a document that, as an example, have something like,

"-sf 6000 means that the of layers is 6,000"

I probably didn't explain myself clearing in my initial post.

The list of options I'm looking for are:

-fa shared
-nf 1
-sf 6000
-rl 40960
-bs 1
-ec 1
-cs 4096
-df {$APP_DATA_DIR}
-gd 1
-go 1
-k 1

Can you explain what these options mean?

Thanks!

**Comment by hariharan-devarajan** [comment]
Ok i added it to the documentation for your reference.

[readme](https://github.com/hariharan-devarajan/dlio_benchmark#command-line-options-for-dlio)

Let me know if you need more explaination.

**Comment by laytonjbgmail** [comment]
Thank you - I quickly looked at the explanation and it looks good.

Jeff

**Comment by hariharan-devarajan** [comment]
Great I will close the issue
