### ISSUE TITLE
can't run dlio_benchmark.py

### ISSUE THREAD

**Issue by nusgnuoy** [hariharan-devarajan/dlio_benchmark#6]
Hello,

I install dlio_benchmark using the following step

Locally
`git clone https://github.com/hariharan-devarajan/dlio_benchmark
cd dlio_benchmark/
python3 -m venv ./venv
source venv/bin/activate
pip install -r requirements.txt 
export PYTHONPATH=$PWD/src:$PYTHONPATH
python ./src/dlio_benchmark.py -h`

after requirements install and run dlio_bnchmark.py but keepp reporting this error.  

ImportError: Extension horovod.tensorflow has not been built: /usr/local/lib/python3.10/dist-packages/horovod/tensorflow/mpi_lib.cpython-310-x86_64-linux-gnu.so not found.

i reinstalled horovod with tensorflow option but stil occu same error. 

is there any solution to solve this error ?

and i want install dlio_benchmark with pip but 
`pip install dlio_benchmark `
cmd dosen't work on ubuntu 22.04.

**Comment by hariharan-devarajan** [comment]
We have migrated the repo to alcf located at https://github.com/argonne-lcf/dlio_benchmark. Can you please check that repo and if issue persists please raise the issue there. Sorry for the inconvenience.

**Comment by nusgnuoy** [comment]
thank you for reply.
